alter table public.ingredients
add column if not exists ingredient_category text not null default 'Pantry';

update public.ingredients
set ingredient_category = case ingredient_id
    when 'ING-001' then 'Coffee & Tea Bases'
    when 'ING-002' then 'Coffee & Tea Bases'
    when 'ING-003' then 'Dairy'
    when 'ING-004' then 'Dairy'
    when 'ING-005' then 'Dairy'
    when 'ING-006' then 'Dairy'
    when 'ING-007' then 'Dairy'
    when 'ING-008' then 'Dairy'
    when 'ING-009' then 'Dairy'
    when 'ING-010' then 'Syrups & Sauces'
    when 'ING-011' then 'Syrups & Sauces'
    when 'ING-012' then 'Syrups & Sauces'
    when 'ING-013' then 'Syrups & Sauces'
    when 'ING-014' then 'Syrups & Sauces'
    when 'ING-015' then 'Syrups & Sauces'
    when 'ING-016' then 'Syrups & Sauces'
    when 'ING-017' then 'Powders & Mixes'
    when 'ING-018' then 'Syrups & Sauces'
    when 'ING-019' then 'Powders & Mixes'
    when 'ING-020' then 'Syrups & Sauces'
    when 'ING-021' then 'Powders & Mixes'
    when 'ING-022' then 'Syrups & Sauces'
    when 'ING-023' then 'Syrups & Sauces'
    when 'ING-024' then 'Powders & Mixes'
    when 'ING-025' then 'Powders & Mixes'
    when 'ING-026' then 'Powders & Mixes'
    when 'ING-027' then 'Powders & Mixes'
    when 'ING-028' then 'Powders & Mixes'
    when 'ING-029' then 'Coffee & Tea Bases'
    when 'ING-030' then 'Syrups & Sauces'
    when 'ING-031' then 'Syrups & Sauces'
    when 'ING-032' then 'Syrups & Sauces'
    when 'ING-033' then 'Syrups & Sauces'
    when 'ING-034' then 'Syrups & Sauces'
    when 'ING-035' then 'Produce'
    when 'ING-036' then 'Pantry'
    when 'ING-037' then 'Powders & Mixes'
    when 'ING-038' then 'Powders & Mixes'
    when 'ING-039' then 'Powders & Mixes'
    when 'ING-040' then 'Frozen & Sides'
    when 'ING-041' then 'Bakery & Bread'
    when 'ING-042' then 'Proteins'
    when 'ING-043' then 'Proteins'
    when 'ING-044' then 'Produce'
    when 'ING-045' then 'Produce'
    when 'ING-046' then 'Produce'
    when 'ING-047' then 'Dairy'
    when 'ING-048' then 'Proteins'
    when 'ING-049' then 'Syrups & Sauces'
    when 'ING-050' then 'Syrups & Sauces'
    when 'ING-051' then 'Syrups & Sauces'
    when 'ING-052' then 'Frozen & Sides'
    when 'ING-053' then 'Frozen & Sides'
    when 'ING-054' then 'Frozen & Sides'
    when 'ING-055' then 'Proteins'
    when 'ING-056' then 'Syrups & Sauces'
    when 'ING-057' then 'Bakery & Bread'
    when 'ING-058' then 'Proteins'
    when 'ING-059' then 'Proteins'
    when 'ING-060' then 'Proteins'
    when 'ING-061' then 'Syrups & Sauces'
    when 'ING-062' then 'Syrups & Sauces'
    when 'ING-063' then 'Syrups & Sauces'
    when 'ING-064' then 'Pantry'
    when 'ING-065' then 'Syrups & Sauces'
    when 'ING-066' then 'Proteins'
    when 'ING-067' then 'Proteins'
    when 'ING-068' then 'Pantry'
    when 'ING-069' then 'Dairy'
    when 'ING-070' then 'Proteins'
    when 'ING-071' then 'Proteins'
    when 'ING-072' then 'Proteins'
    when 'ING-073' then 'Syrups & Sauces'
    when 'ING-074' then 'Proteins'
    when 'ING-075' then 'Beverages'
    when 'ING-076' then 'Syrups & Sauces'
    when 'ING-077' then 'Coffee & Tea Bases'
    when 'ING-078' then 'Syrups & Sauces'
    when 'ING-079' then 'Syrups & Sauces'
    when 'ING-080' then 'Syrups & Sauces'
    when 'ING-081' then 'Syrups & Sauces'
    when 'ING-082' then 'Beverages'
    when 'ING-083' then 'Beverages'
    else ingredient_category
end;

create index if not exists idx_ingredients_category
    on public.ingredients(ingredient_category);
